#ifndef CONFIG_H
#define CONFIG_H
/* the following lines are generated by the configure script */
/* DO NOT EDIT THIS FILE BUT THOSE INSTEAD: */
/* config.h.sk */

#undef DEBUG
#define PRODUCT_ID "ECIADSL"
#define PRODUCT_NAME "ECIADSL USB modem driver"
#define PRODUCT_VERSION "0.8"
#define ETC_PATH "/"
#define ETC_DIR "etc"
#define CONF_PATH "/"
#define CONF_DIR "etc/eciadsl"
#define DOC_PATH "/usr/local/"
#define DOC_DIR "doc/eciadsl"
#endif
